#define table-of-contents 180
#define ExternalAppointment 170
#define Calendar 40
#define customer 560
#define view-customers 210
#define add-a-registered-customer 270
#define edit-a-customer 540
#define edit-customer-contact 350
#define deleting-a-registered-customer 290
#define complaints 220
#define add-an-unregistered-customer 330
#define unregistered-cust-contact-tab 340
#define linking-user 360
#define adding-subscription-for-an-active-customer 310
#define creating-filters 320
#define terminating-an-active-customer 300
#define viewing-subscribers 490
#define adding-subscriptions 430
#define defining-discounts-for-subscriptions 460
#define defining-fees-for-subscriptions 450
#define defining-rules-for-subscriptions 440
#define managing-subscriptions 420
#define adding-subscribers 480
#define modifying-subscriber-details 510
#define adding-filters-for-subscribers 500
#define viewing-subscription-applications 390
#define adding-filters-for-subscription-applications 590
#define adding-complaints 370
#define filtering-complaints 380
#define subscribing-for-a-course 520
#define applying-for-subscription 580
#define subscribed-successfully 600

